# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{labor}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brett Buddin"]
  s.date = %q{2011-02-17}
  s.description = %q{      Wrapper for Gearman to make workers easier to create and manage.
}
  s.email = %q{brett@intraspirit.net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "labor.gemspec",
    "lib/labor.rb",
    "lib/labor/config.rb",
    "lib/labor/core_ext.rb",
    "lib/labor/helpers.rb",
    "lib/labor/tasks.rb",
    "lib/labor/version.rb",
    "lib/labor/worker.rb"
  ]
  s.homepage = %q{http://github.com/brettbuddin/labor}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Wrapper for Gearman to make workers easier to create and manage.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gearman-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<gearman-ruby>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<gearman-ruby>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

